### ISSUE TITLE
Preview does not work, but running the app works

### ISSUE THREAD

**Issue by TheAirBlow** [ForNeVeR/AvaloniaRider#180] opened 2022-01-21 12:51 UTC
Logs (I'm unsure which one of these is the one I need):
```
"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig C:\Users\TheAirBlow\Desktop\blowaunch\Blowaunch.AvaloniaApp\bin\Debug\net5.0\Blowaunch.AvaloniaApp.runtimeconfig.json --depsfile C:\Users\TheAirBlow\Desktop\blowaunch\Blowaunch.AvaloniaApp\bin\Debug\net5.0\Blowaunch.AvaloniaApp.deps.json C:\Users\TheAirBlow\.nuget\packages\avalonia\0.10.11\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:49857/ --method avalonia-remote C:\Users\TheAirBlow\Desktop\blowaunch\Blowaunch.AvaloniaApp\bin\Debug\net5.0\Blowaunch.AvaloniaApp.dll
Obtaining AppBuilder instance from Blowaunch.AvaloniaApp.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 59
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 71
Process terminated with exit code 1
```
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.)
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   at Avalonia.Remote.Protocol.TcpTransportBase.Connect(IPAddress address, Int32 port) in /_/src/Avalonia.Remote.Protocol/TcpTransportBase.cs:line 72
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.CreateTransport(CommandLineArgs args) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 120
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 164
   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47
```

Preview:
![Preview](https://user-images.githubusercontent.com/68467762/150529649-b395a1bf-6af0-41fb-883b-a847eb1b4bad.png)
Application:
![Running](https://user-images.githubusercontent.com/68467762/150529702-e92400cf-120f-493b-969e-0974c53f732c.png)

Source code: [GitHub Link](https://github.com/TheAirBlow/blowaunch/tree/main/Blowaunch.AvaloniaApp)
Commenting out versions loader and the `ComboBox.ItemTemplate` doesn't work.

**Comment by ForNeVeR** [comment] 2022-01-22 13:43
This preview works for me. Could you please share the IDE logs? **Help → Collect Logs**.

**Comment by ForNeVeR** [comment] 2022-02-20 13:26
Without your feedback, the issue is non-actionable. Closed.

**Comment by TheAirBlow** [comment] 2022-04-02 10:43
@ForNeVeR
[rider-logs-20220402-15425410188584362994188554.zip](https://github.com/ForNeVeR/AvaloniaRider/files/8402327/rider-logs-20220402-15425410188584362994188554.zip)

**Comment by TheAirBlow** [comment] 2022-04-02 10:45
Avalonia tab below:
![изображение](https://user-images.githubusercontent.com/68467762/161379644-b94be9dd-1397-4009-8669-ab2f2555afb9.png)
![изображение](https://user-images.githubusercontent.com/68467762/161379651-8d3b01da-0d3b-4c16-8738-2c07b3d503ea.png)

**Comment by ForNeVeR** [comment] 2022-04-02 10:48
@TheAirBlow, it looks like the following issue is the main problem:
```
15:42:51.023 | INFO  | AvaloniaPreviewerSession       | Error from UpdateXamlResultMessage: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files\JetBrains\JetBrains Rider 2021.3\jbr\bin\config.json' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Blowaunch.AvaloniaApp.Views.MainWindow..ctor() in D:\CSharp\blowaunch\Blowaunch.AvaloniaApp\Views\MainWindow.axaml.cs:line 31
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadOrPopulate(Type created, Object rootInstance) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 229
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 197
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 158
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/AvaloniaXamlIlRuntimeCompiler.cs:line 258
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(Stream stream, Assembly localAsm, Object o, Uri baseUri, Boolean designMode) in /_/src/tools/Avalonia.Designer.HostApp/DesignXamlLoader.cs:line 13
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath) in /_/src/Avalonia.DesignerSupport/DesignWindowLoader.cs:line 33
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0() in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 233
```

This should be addressed by #191.
   
Please try updating to Rider EAP and the latest version of the plugin.

**Closed by ForNeVeR** 2022-04-02 10:48 UTC
Labels: kind:bug

**Comment by TheAirBlow** [comment] 2022-04-02 10:55
!= Updated the plugin
Testing if it does work
!= Not updated Rider yet

**Comment by TheAirBlow** [comment] 2022-04-02 10:59
@ForNeVeR the `config.json` is the configuration file that my app uses.
It creates a new config if it's not present, and it worked when I ran the app.

Looking into fixing it. Issue solved.

**Comment by C6OI** [comment] 2022-09-18 11:33
I have the same error.
My application needs to download some files to the AppData directory. The preview was working yesterday when I added the files download, I saved the changes to github, but today previewer crashes when I try to make changes to the axaml files.
I rolled back to an earlier version where there was no file download yet and the previewer works fine.

Avalonia tab:
```
Obtaining AppBuilder instance from EELauncher.Program.BuildAvaloniaApp
Initializing application in design mode
Sending StartDesignerSessionMessage
Process terminated with exit code 0
```
Exception: 
![image](https://user-images.githubusercontent.com/59257047/190898467-a954a64a-ba8b-4a1d-962a-252bb04ae4b5.png)
Logs:
[rider-logs-20220918-1553309288692697903174440.zip](https://github.com/ForNeVeR/AvaloniaRider/files/9593855/rider-logs-20220918-1553309288692697903174440.zip)

**Comment by TheAirBlow** [comment] 2022-09-18 11:56
> I have the same error. My application needs to download some files to the AppData directory. The preview was working yesterday when I added the files download, I saved the changes to github, but today previewer crashes when I try to make changes to the axaml files. I rolled back to an earlier version where there was no file download yet and the previewer works fine.
> 
> Avalonia tab:
> 
> ```
> Obtaining AppBuilder instance from EELauncher.Program.BuildAvaloniaApp
> Initializing application in design mode
> Sending StartDesignerSessionMessage
> Process terminated with exit code 0
> ```
> 
> Exception: ![image](https://user-images.githubusercontent.com/59257047/190898467-a954a64a-ba8b-4a1d-962a-252bb04ae4b5.png) Logs: [rider-logs-20220918-1553309288692697903174440.zip](https://github.com/ForNeVeR/AvaloniaRider/files/9593855/rider-logs-20220918-1553309288692697903174440.zip)

Make some safeguards that prevent the app from crashing. It is 100% because of your own code. The preview runs all of this code in a temporary folder, so you have to adapt to these conditions. There are probably other restrictions, so try to find them.
