### ISSUE TITLE
How to show Design Preview window?

### ISSUE THREAD

**Issue by Shadow4walker** [ForNeVeR/AvaloniaRider#103] opened 2020-12-17 19:19 UTC
I've just installed this plugin but after opening the avalonia view '.axaml' nothing has showing and there's no preview tab or anything! so how could i show the preview Designer?

Rider version
![ScreenShot_20201217211739](https://user-images.githubusercontent.com/43580244/102532921-60a6dc00-40ad-11eb-920b-7009f849dcd1.png)

**Comment by ForNeVeR** [comment] 2020-12-19 14:17
This is a duplicate of #65. Isn't done yet.

**Closed by ForNeVeR** 2020-12-19 14:17 UTC
