### ISSUE TITLE
Actipro library crashes the previewer

### ISSUE THREAD

**Issue by PerfectlyFineCode** [ForNeVeR/AvaloniaRider#336] opened 2024-04-11 10:44 UTC
Actipro's free UI library "crashes" the previewer, no errors in Rider and no special logs.
Previewer just doesn't show up when adding
```xaml
    <Application.Styles>
        <actipro:ModernTheme />
    </Application.Styles>
```
 to App styles and when I remove the ModernTheme and add Avalonia's FluentTheme it shows up again.

```xml
<PackageReference Include="ActiproSoftware.Controls.Avalonia" Version="23.1.3" />
```

Rider:
```
  JetBrains Rider 2023.3.4
  Build #RD-233.14475.66, built on March 6, 2024
  Runtime version: 17.0.10+1-b1087.17 amd64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  Windows 11.
  avalonia-rider (1.3.0)
```

**Comment by ForNeVeR** [comment] 2024-04-11 20:59
Does the previewer print any logs?

**Comment by PerfectlyFineCode** [comment] 2024-04-12 07:24
> Does the previewer print any logs?

```
"C:\Program Files\dotnet\dotnet.exe" exec --runtimeconfig C:\Users\{USERNAME}\RiderProjects\TestBug\TestBug\bin\Debug\net8.0\TestBug.runtimeconfig.json --depsfile C:\Users\{USERNAME}\RiderProjects\TestBug\TestBug\bin\Debug\net8.0\TestBug.deps.json C:\Users\{USERNAME}\.nuget\packages\avalonia\11.0.10\buildTransitive\..\tools\netcoreapp2.0\designer\Avalonia.Designer.HostApp.dll --transport tcp-bson://127.0.0.1:51114/ --method avalonia-remote C:\Users\{USERNAME}\RiderProjects\TestBug\TestBug\bin\Debug\net8.0\TestBug.dll
Initializing application in design mode
Obtaining AppBuilder instance from TestBug.Program
Sending StartDesignerSessionMessage
```

**Comment by PerfectlyFineCode** [comment] 2024-04-12 07:30
Seems like this is the thing that makes it stop working
```xml
<Window ... 
                xmlns:actipro="http://schemas.actiprosoftware.com/avaloniaui"
                xmlns:material="clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia"
                ... >
        <actipro:ChromedTitleBar DockPanel.Dock="Top"
                                 Content="{CompiledBinding RelativeSource={RelativeSource  Mode=FindAncestor, AncestorType=Window}, Path=Title}"
                                 Background="Transparent">
            <actipro:ChromedTitleBar.RightContent>
                <StackPanel Orientation="Horizontal">
                    <Button BorderBrush="{x:Null}"
                            BorderThickness="0">
                            <material:MaterialIcon Width="24"
                                                   Height="24"/>
                    </Button>
                </StackPanel>
            </actipro:ChromedTitleBar.RightContent>
        </actipro:ChromedTitleBar>
</Window>
```
So it might not be entirely actipro's fault but also 
```xml
<PackageReference Include="Material.Icons.Avalonia" Version="2.1.9" />
```

**Comment by ForNeVeR** [comment] 2024-04-12 15:09
Please check the IDE logs. Are there any lines with severity `WARN` or `SEVERE` in them?

**Comment by PerfectlyFineCode** [comment] 2024-04-12 15:19
> Please check the IDE logs. Are there any lines with severity `WARN` or `SEVERE` in them?

```
2024-04-12 17:17:18,850 [  19198]   WARN - #me.fornever.avaloniarider.idea.editor.BitmapPreviewEditorComponent - XAML update error: XamlParseException at 29:26: Unable to resolve type MaterialIcon from namespace clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia Line 29, position 26.
XamlX.XamlParseException: Unable to resolve type MaterialIcon from namespace clr-namespace:Material.Icons.Avalonia;assembly=Material.Icons.Avalonia Line 29, position 26.
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveTypeCore(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict)
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, String xmlns, String name, Boolean isMarkupExtension, List`1 typeArguments, IXamlLineInfo lineInfo, Boolean strict)
   at XamlX.Transform.Transformers.TypeReferenceResolver.ResolveType(AstTransformationContext context, XamlAstXmlTypeReference xmlref, Boolean strict)
   at XamlX.Transform.Transformers.TypeReferenceResolver.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstXamlPropertyValueNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Transform.AstTransformationContext.Visit(IXamlAstNode root, IXamlAstTransformer transformer)
   at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadGroupSreCore(IReadOnlyCollection`1 documents, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass18_0.<OnTransportMessage>b__0()
2024-04-12 17:17:18,911 [  19259]   INFO - #c.i.w.i.i.EntitiesOrphanageImpl - Update orphanage. 0 modules added
2024-04-12 17:17:19,161 [  19509]   WARN - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession - Message ignored: RequestViewportResizeMessage(width=273.0, height=19.0)
2024-04-12 17:17:19,162 [  19510]   WARN - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession - Message ignored: RequestViewportResizeMessage(width=273.0, height=19.0)
2024-04-12 17:17:19,217 [  19565]   WARN - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession - Message ignored: RequestViewportResizeMessage(width=273.0, height=19.0)
2024-04-12 17:17:19,268 [  19616]   WARN - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession - Message ignored: RequestViewportResizeMessage(width=342.0, height=24.0)
2024-04-12 17:17:19,313 [  19661]   WARN - #me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession - Message ignored: RequestViewportResizeMessage(width=342.0, height=24.0)

```

**Comment by ForNeVeR** [comment] 2024-04-12 15:28
That's it, that's the reason. What it cannot parse is a question for Avalonia or `Material.Icons.Avalonia` folks, I don't know that.

I am closing this as a duplicate of #316 for now: we should have better error reporting.

**Closed by ForNeVeR** 2024-04-12 15:28 UTC
Labels: status:waiting-for-info
