### ISSUE TITLE
Dont work with big windows

### ISSUE THREAD

**Issue by CreateLab** [ForNeVeR/AvaloniaRider#92] opened 2020-10-24 13:24 UTC
Dont show anything with window from material ui demo.
https://github.com/AvaloniaUtils/material.avalonia/blob/master/Material.Demo/MainWindow.xaml

**Comment by CreateLab** [comment] 2020-10-24 13:25
![image](https://user-images.githubusercontent.com/33497292/97082871-73ed7c00-1615-11eb-9f0b-ae521ec62069.png)

**Comment by ForNeVeR** [comment] 2020-10-24 14:09
Could you show the logs?

**Comment by CreateLab** [comment] 2020-10-24 15:52
```
24.10.2020
18:51	External file changes sync may be slow: The current inotify(7) watch limit is too low. More details.

18:51	Build succeeded at 18:51:52
```
Logs of plugin

**Comment by CreateLab** [comment] 2020-10-24 15:53
[rider-logs-20201024-185246.zip](https://github.com/ForNeVeR/AvaloniaRider/files/5433147/rider-logs-20201024-185246.zip)

**Comment by ForNeVeR** [comment] 2020-10-25 06:34
Still no logs from the previewer.

**Comment by wdcossey** [comment] 2020-10-25 13:54
Just debugging it locally, throws the exception below:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.MethodAccessException: Attempt by method 'Builder_1d26bc8f17ab429aa6717cce8e512df2_avares://Material.Demo/MainWindow.xaml.__AvaloniaXamlIlPopulate(System.IServiceProvider, Material.Demo.MainWindow)' to access method 'Material.Demo.MainWindow.BaseThemeChanged(System.Object, Avalonia.Interactivity.RoutedEventArgs)' failed.
   at Builder_1d26bc8f17ab429aa6717cce8e512df2_avares://Material.Demo/MainWindow.xaml.__AvaloniaXamlIlPopulate(IServiceProvider , MainWindow )
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.<>c__DisplayClass12_0.<LoadOrPopulate>b__0(Object target)
   at Material.Demo.MainWindow.!XamlIlPopulateTrampoline(MainWindow )
   at Material.Demo.MainWindow.InitializeComponent() in C:\Users\<%user%>\RiderProjects\material.avalonia\Material.Demo\MainWindow.xaml.cs:line 22
   at Material.Demo.MainWindow..ctor() in C:\Users\<%user%>\RiderProjects\material.avalonia\Material.Demo\MainWindow.xaml.cs:line 17
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadOrPopulate(Type created, Object rootInstance)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode)
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(Stream stream, Assembly localAsm, Object o, Uri baseUri, Boolean designMode)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass17_0.<OnTransportMessage>b__0()
```

The reason you don't see an exception in the UI is because there's a frame message after the exception (the exception is shown for a brief ms but immediately hidden)

Message Flow with `MainWindow.xaml`
1. StartDesignerSessionMessage
2. UpdateXamlResultMessage
3. FrameMessage

**Comment by wdcossey** [comment] 2020-10-25 14:04
The previewer does actually work if you fix the offending code in `MainWindow.xaml` and `MainWindow.cs`

![image](https://user-images.githubusercontent.com/1089478/97109373-cccb1c00-16ca-11eb-89c3-1f2f9be1e5de.png)

**Comment by wdcossey** [comment] 2020-10-25 14:09
@CreateLab 

inside `MainWindow.xaml.cs` change the following:

```
        private void BaseThemeChanged(object sender, RoutedEventArgs args) {
            ...
        }

        private void BaseThemeColorChanged(object sender, RoutedEventArgs args) {
            ...
        }
```

to

```
        public void BaseThemeChanged(object sender, RoutedEventArgs args) {
            ...
        }

        public void BaseThemeColorChanged(object sender, RoutedEventArgs args) {
            ...
        }
```

Close `MainWindow.xaml.cs`
Close `MainWindow.xaml`
Rebuild the project `Material.Demo.csproj`
Open `MainWindow.xaml` again.

**Comment by CreateLab** [comment] 2020-10-25 15:26
@wdcossey yep it's work, but as I think it's a bug, cause app works with `private` key word too

**Comment by wdcossey** [comment] 2020-10-25 16:03
It's possible that Avalonia use private methods on code behind. Or is this the Material add-on doing this?

'access method 'Material.Demo.MainWindow.BaseThemeChanged(System.Object, Avalonia.Interactivity.RoutedEventArgs)' failed'

That exception is thrown from the Avalonia renderer and not AvaloniaRider, AvaloniaRider simply catches the exception from the Renderer.

**Comment by CreateLab** [comment] 2020-10-26 14:30
@wdcossey avalonia allow me to do it, that's fun, that avalonia allow me to do it and throw exception.

**Comment by kekekeks** [comment] 2020-10-26 14:56
That's caused by previewer process emitting a separate assembly for compiled XAML. It can probably be fixed through emitting IgnoresAccessChecksFromAttribute on said assembly, but that has to be confirmed.

**Comment by ForNeVeR** [comment] 2020-10-29 15:51
@CreateLab, could you please report the issue to the main Avalonia repository?

**Comment by rstm-sf** [comment] 2020-10-31 21:51
A similar request already exists https://github.com/AvaloniaUI/Avalonia/issues/4262

**Comment by ForNeVeR** [comment] 2020-11-01 06:47
Thanks! This is, indeed, a duplicate of that issue.

**Closed by ForNeVeR** 2020-11-01 06:47 UTC
Labels: kind:bug
