### ISSUE TITLE
Support monitor DPI

### ISSUE THREAD

**Issue by danwalmsley** [ForNeVeR/AvaloniaRider#109] opened 2021-02-11 13:18 UTC
Plugin always renders at 96dpi even on high dpi displays.

In AvalonStudio I implemented support for this and for Zooming by:

https://github.com/VitalElement/AvalonStudio/blob/develop/AvalonStudio/AvalonStudio.Languages.Xaml/RemoteWidget.cs#L29-L46

**Comment by rstm-sf** [comment] 2021-02-13 04:23
Duplicate of https://github.com/ForNeVeR/AvaloniaRider/issues/9

**Comment by ForNeVeR** [comment] 2021-02-22 14:31
Yes, this is a duplicate.

**Closed by ForNeVeR** 2021-02-22 14:31 UTC
