### ISSUE TITLE
Preview shows neverending loading wheel

### ISSUE THREAD

**Issue by SCLD-GHettinger** [ForNeVeR/AvaloniaRider#182] opened 2022-02-04 23:09 UTC
![image](https://user-images.githubusercontent.com/89482547/152615069-1bd31f3e-ff7b-4082-b263-29c17878ec6c.png)

**Comment by ForNeVeR** [comment] 2022-02-05 15:39
Any logs or something? How to reproduce the issue?

**Comment by jvbsl** [comment] 2022-02-20 09:45
Don't know if it is completely the same issue but for me the problem is here:
https://github.com/ForNeVeR/AvaloniaRider/blob/58e0611832a87069bf59e2f9a63c03beb96d0ca8/src/dotnet/AvaloniaRider.Plugin/AvaloniaRiderProjectModelHost.cs#L60

```
2022-02-20 10:32:19,135 [  57674]   INFO - #m.f.a.i.e.a.RunnableAssemblySelectorAction - Target project path "/home/username/Projects/AvaloniaTest/AvaloniaTest.csproj" is also available for selection
2022-02-20 10:32:19,137 [  57676]   INFO - #m.f.a.i.e.a.RunnableAssemblySelectorAction - Target project path "/home/username/Projects/AvaloniaTest/AvaloniaTest.csproj" is also available for selection
2022-02-20 10:32:19,161 [  57700]   INFO - #m.f.a.i.e.a.RunnableAssemblySelectorAction - Determining target project path
2022-02-20 10:32:19,161 [  57700]   INFO - #m.f.a.i.e.a.RunnableAssemblySelectorAction - Trying to load saved project
2022-02-20 10:32:19,161 [  57700]   INFO - #m.f.a.i.e.a.RunnableAssemblySelectorAction - Saved project file path: /home/username/Projects/AvaloniaTest/AvaloniaTest.csproj
2022-02-20 10:32:19,162 [  57701]   INFO - #m.f.a.i.e.a.RunnableAssemblySelectorAction - Synchronization with saved project file: success
2022-02-20 10:32:19,187 [  57726]   INFO - #m.f.a.p.AvaloniaPreviewerSessionController - Controller state change: isBuilding = false, projectFilePath = /home/username/Projects/AvaloniaTest/AvaloniaTest.csproj
2022-02-20 10:32:19,187 [  57726]   INFO - #m.f.a.p.AvaloniaPreviewerSessionController - Force start preview for file:///home/username/Projects/AvaloniaTest/MainWindow.xaml
2022-02-20 10:32:19,190 [  57729]   INFO - #m.f.a.p.AvaloniaPreviewerSessionController - Receiving the containing project for the file file:///home/username/Projects/AvaloniaTest/MainWindow.xaml
2022-02-20 10:32:19,537 [  58076]   INFO - #m.f.a.i.e.BitmapPreviewEditorComponent - Status: Connecting
2022-02-20 10:32:19,825 [  58364]   INFO - #m.f.a.p.AvaloniaPreviewerSessionController - Calculating a project output for the project /home/username/Projects/AvaloniaTest/AvaloniaTest.csproj
2022-02-20 10:32:21,159 [  59698]   INFO - #c.j.r.e.LogsAttachListener - Packed logs in 1533ms to /tmp/rider-logs-attachment4.tar.xz
2022-02-20 10:32:22,382 [  60921] SEVERE - #m.f.a.p.AvaloniaPreviewerSessionController - Method not found: '!!0 JetBrains.Diagnostics.Assertion.NotNull(!!0)'., reason: System.MissingMethodException: Method not found: '!!0 JetBrains.Diagnostics.Assertion.NotNull(!!0)'.
   at ReSharperPlugin.AvaloniaRider.AvaloniaRiderProjectModelHost.GetProjectOutputModel(Lifetime lifetime, RdGetProjectOutputArgs args)
   at JetBrains.Rd.Tasks.RdCall`2.OnWireReceived(UnsafeReader reader)
com.jetbrains.rd.util.reactive.RdFault: Method not found: '!!0 JetBrains.Diagnostics.Assertion.NotNull(!!0)'., reason: System.MissingMethodException: Method not found: '!!0 JetBrains.Diagnostics.Assertion.NotNull(!!0)'.
   at ReSharperPlugin.AvaloniaRider.AvaloniaRiderProjectModelHost.GetProjectOutputModel(Lifetime lifetime, RdGetProjectOutputArgs args)
   at JetBrains.Rd.Tasks.RdCall`2.OnWireReceived(UnsafeReader reader)
	at com.jetbrains.rd.framework.RdTaskResult$Companion.read(TaskInterfaces.kt:30)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask.onWireReceived(RdTask.kt:98)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:802)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2022-02-20 10:32:22,386 [  60925] SEVERE - #m.f.a.p.AvaloniaPreviewerSessionController - JetBrains Rider 2022.1 EAP 3  Build #RD-221.4501.83
2022-02-20 10:32:22,386 [  60925] SEVERE - #m.f.a.p.AvaloniaPreviewerSessionController - JDK: 11.0.14; VM: Dynamic Code Evolution 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-02-20 10:32:22,386 [  60925] SEVERE - #m.f.a.p.AvaloniaPreviewerSessionController - OS: Linux
```

**Comment by ForNeVeR** [comment] 2022-02-20 09:50
@jvbsl, that's a new one in EAP 3, I think, so it cannot be the same problem @SCLD-GHettinger was having.

**Comment by jvbsl** [comment] 2022-02-20 10:05
Thanks a lot for the fast reply.
Yeah that makes sense, didn't think about EAP 3 not being available 15 days ago.

But I updated rider because I had the loading wheel in the hopes of it working with a newer version. unfortunately I can't go back to my previous version(don't know if it was EAP 1 or 2 could've been even some nightly version as it was 213.6995.5).

Should I try the same thing with 2021.3.3(213.6775.4) for error logs, or do you even want to support "old" versions going forward?

**Comment by ForNeVeR** [comment] 2022-02-20 11:51
There should be some versions of the plugin published for the older (well, actually, that's _stable_) version of Rider, so you _could_ try that if you wish. Though, for now, I think I should fix the issue for EAP3 (and it actually only takes a recompile, I hope).

**Comment by ForNeVeR** [comment] 2022-02-20 13:28
Anyway, I got no feedback from the issue reporter in 15 days, so I'm closing the issue.

The problem with "Method not found" should be fixed by the latest build, which will be published to the plugin Marketplace soon (in an hour or so).

**Closed by ForNeVeR** 2022-02-20 13:28 UTC
Labels: status:waiting-for-info

**Comment by SCLD-GHettinger** [comment] 2022-02-23 00:38
> Any logs or something? How to reproduce the issue?

What logs? Where can I find these logs (I'm unfamiliar with Rider). To reproduce the issue, I open up my project and open a .axaml file.

**Comment by SCLD-GHettinger** [comment] 2022-02-23 00:41
I found the logs, but I can't paste the whole thing, it's too long for github.

**Comment by ForNeVeR** [comment] 2022-02-27 14:34
Doesn't they way what's gone wrong?

**Comment by SCLD-GHettinger** [comment] 2022-03-01 17:47
Does this give you any useful info?

19:32:36.215 | INFO  | AvaloniaPreviewerSessionController | Controller state change: isBuilding = false, projectFilePath = null
19:32:36.216 | INFO  | AvaloniaPreviewerSessionController | Suspending preview for file://C:/Users/gHettinger/source/repos/ConfigOS-Command-Center-Client/ConfigOS Command Center Client/Views/MainWindow/MainWorkspaceView.axaml
19:32:36.243 | INFO  | BitmapPreviewEditorComponent   | Status: Suspended
19:32:36.254 | WARN  | ActionToolbarImpl              | 'EditorToolbar' toolbar by default uses any focused component to update its actions. Toolbar actions that need local UI context would be incorrectly disabled. Please call toolbar.setTargetComponent() explicitly.
java.lang.Throwable: toolbar creation trace
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:115)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:425)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:420)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewEditorBase.createToolbarComponent(AvaloniaPreviewEditorBase.kt:99)
	at me.fornever.avaloniarider.idea.editor.AvaloniaRemotePreviewEditor.<init>(AvaloniaRemotePreviewEditor.kt:16)
	at me.fornever.avaloniarider.idea.editor.AvaloniaPreviewerXamlEditorExtension.createEditor(AvaloniaPreviewerXamlEditorExtension.kt:22)
	at com.jetbrains.rider.xaml.splitEditor.XamlSplitEditorImpl$loadPreviewEditorThroughExtensions$1.invoke(XamlSplitEditorImpl.kt:150)
	at com.jetbrains.rider.xaml.splitEditor.XamlSplitEditorImpl$loadPreviewEditorThroughExtensions$1.invoke(XamlSplitEditorImpl.kt:43)
	at com.jetbrains.rider.xaml.MarkupPreviewHost$executeWithPreviewPlatform$1$1.invoke(MarkupPreviewHost.kt:21)
	at com.jetbrains.rider.xaml.MarkupPreviewHost$executeWithPreviewPlatform$1$1.invoke(MarkupPreviewHost.kt:15)
	at com.jetbrains.rd.framework.impl.RdTaskKt$startAndAdviseSuccess$1.invoke(RdTask.kt:21)
	at com.jetbrains.rd.framework.impl.RdTaskKt$startAndAdviseSuccess$1.invoke(RdTask.kt)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty$WriteOnceSignal.fire(Property.kt:120)
	at com.jetbrains.rd.util.reactive.WriteOnceProperty.setIfEmpty(Property.kt:84)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask.onWireReceived(RdTask.kt:97)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ForNeVeR** [comment] 2022-03-06 15:42
Nope, unfortunately.
