### ISSUE TITLE
Is it possible to scale the preview like in VS ?

### ISSUE THREAD

**Issue by DrWenz** [ForNeVeR/AvaloniaRider#178] opened 2022-01-01 11:08 UTC

**Comment by ForNeVeR** [comment] 2022-01-01 13:15
Duplicate of #110, I think.

**Closed by ForNeVeR** 2022-01-01 13:15 UTC

**Comment by DrWenz** [comment] 2022-01-02 08:27
yeah, but how can I set the Scale in Rider ?

**Comment by ForNeVeR** [comment] 2022-01-02 10:04
I don't know of any such way, sorry.
