### ISSUE TITLE
Exception in the plugin.

### ISSUE THREAD

**Issue by VirtualMaestro** [ForNeVeR/AvaloniaRider#210] opened 2022-06-12 15:59 UTC
Hello developers,
I've just started with Avalonia and did all the prerequisites. 
The designer doesn't open, and the plugin throws an exception (the whole stacktrace file I've attached): 
```
Unhandled coroutine throwable

java.util.NoSuchElementException: Sequence is empty.
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:111)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt:51)
	at me.fornever.avaloniarider.rider.ProjectModelNodeExKt$getProjectContainingFile$2.invoke(ProjectModelNodeEx.kt:40)
```

The rider version is 2022.1.2
[stacktrace.txt](https://github.com/ForNeVeR/AvaloniaRider/files/8886198/stacktrace.txt)

(I'm following this tutorial https://docs.avaloniaui.net/tutorials/todo-list-app)

Thank you in advance

**Comment by ForNeVeR** [comment] 2022-06-14 16:36
Duplicate of #156.

**Closed by ForNeVeR** 2022-06-14 16:36 UTC
