### ISSUE TITLE
Allow changing the default open position of the previewer (or remember it)

### ISSUE THREAD

**Issue by colejohnson66** [ForNeVeR/AvaloniaRider#229] opened 2022-10-10 19:08 UTC
Opening the previewer below is very annoying for our project. We are constantly having to change to be on the side, but it never remembers the width.

Ideally, the width/height and position would be remembered, but a setting to set the default would work too.

**Comment by ForNeVeR** [comment] 2022-10-12 21:29
This is a duplicate of #143.

**Closed by ForNeVeR** 2022-10-12 21:29 UTC
Labels: kind:enhancement
