### ISSUE TITLE
No preview in libs

### ISSUE THREAD

**Issue by CreateLab** [ForNeVeR/AvaloniaRider#93] opened 2020-11-01 07:37 UTC
![image](https://user-images.githubusercontent.com/33497292/97797454-2b921780-1c2e-11eb-852f-534777f5f54d.png)

Can't see my window in plugin
https://github.com/AvaloniaUtils/MessageBox.Avalonia/blob/master/src/MessageBox.Avalonia/Views/MsBoxCustomWindow.xaml

**Comment by ForNeVeR** [comment] 2020-11-01 07:40
Duplicate of #55.

**Closed by ForNeVeR** 2020-11-01 07:40 UTC
