### ISSUE TITLE
XAML Preview Doesn't Load when using 3rd Party Widgets

### ISSUE THREAD

**Issue by begleysm** [ForNeVeR/AvaloniaRider#244] opened 2022-11-28 15:50 UTC
The XAML Preview doesn't ever load if there is a Widget that comes from a 3rd part source like [LiveCharts2](https://github.com/beto-rodriguez/LiveCharts2).

Here's code in which the Preview never loads
![image](https://user-images.githubusercontent.com/1275999/204321489-2b321a16-9b1f-4ed3-9609-e6353225b2bc.png)

Here's code in which the Preview does load (because the offending widgets are commented out)
![image](https://user-images.githubusercontent.com/1275999/204321532-07360205-a4f4-4295-9c53-4ff810a3aeca.png)

Both versions (with & without comments) will successfully build & run.

I wouldn't expect the Previewer to know how to accurately preview 3rd party widgets but it would be nice if it would still load and would simply leave a blank or colored box in place of.

**Comment by begleysm** [comment] 2022-11-28 20:44
As per https://github.com/AvaloniaUI/AvaloniaVS/issues/271#issuecomment-1329547781 this can be solved by adding `GC.KeepAlive(typeof(YourControlType).Assembly)` to your `BuildAvaloniaApp`.

However, I still wonder is this not something that can be handled by the Plugin exclusivly? The same issue happens with the Visual Studio Plugin.

**Comment by ForNeVeR** [comment] 2022-11-30 22:51
Thanks to your feedback here and on the AvaloniaVS repo, we were able to conclude that this should be fixed in Avalonia previewer core. Closed as duplicate of https://github.com/AvaloniaUI/Avalonia/issues/9574.

**Closed by ForNeVeR** 2022-11-30 22:51 UTC
Labels: kind:bug
