### ISSUE TITLE
Preview is not shown, no error message

### ISSUE THREAD

**Issue by SimonORorke** [ForNeVeR/AvaloniaRider#337] opened 2024-04-18 04:40 UTC
In Windows, I'm working on my first Avalonia UI project and have not seen the XAML preview with any of the XAML files. All my XAML files contain the section that is automatically included on XAML creation to enable preview:
```
<Design.DataContext>
    <!-- This only sets the DataContext for the previewer in an IDE. -->
    <viewModel:MainWindowViewModel />
</Design.DataContext>
```
The first version of the preview plugin I installed was 1.3.0 with Rider 2023.3.4.  Now I'm on 1.3.2 with Rider 2024.1. Neither has worked for me.
![Plugins](https://github.com/ForNeVeR/AvaloniaRider/assets/79874679/baf3bbe9-e08f-49fc-a107-b6531d025b71)

**What steps will reproduce the issue?**
Create a solution using the Avalonia .NET MVVM App template.
Open MainWindow.axaml.

**What is the expected result?**
XAML Preview should be shown along with the XAML.

**What happens instead?**
XAML Preview is not shown. There is no error message that I can see.

I previously raised this issue with JetBrains support.  Before they asked me to raise the issue at this plugin repository, they mentioned that they could not reproduce the issue.  If there is something specific in my environment that is contributing to the problem, I'd be happy to provide diagnostics.  Is there a way I can get Rider to run the plugin's source code so I can trace what's happening?

**Comment by ForNeVeR** [comment] 2024-04-18 21:42
Ok, I have re-checked with the latest **Avalonia.Templates** on the latest stable version of Rider, and I can't reproduce any issue. Could you please show a screenshot of your whole IDE window? Where do you expect to see the preview? What is shown instead?

**Comment by SimonORorke** [comment] 2024-04-19 01:40
![AvaloniaPreviewTest – Whole IDE](https://github.com/ForNeVeR/AvaloniaRider/assets/79874679/eb92332f-ed0e-4b45-8545-ab57bc451842)

**Comment by ForNeVeR** [comment] 2024-04-19 08:54
Try interacting with these buttons. Will it appear?

![image](https://github.com/ForNeVeR/AvaloniaRider/assets/92793/3793318b-b160-41dd-90f4-8ea12fe51d47)

**Comment by SimonORorke** [comment] 2024-04-19 09:42
Yes, on my little test application, clicking the Edit and Preview or Preview Only buttons does show the preview.  Thanks!  As you can imagine, I did think there ought to be a way to turn the preview on and off, but my researches came up with nothing.  I think my mistake was to look for how to do it specifically for the Avalonia preview.  As I now realise, those butttons would work for previews of other user interfaces.  As such, I expect they must be described in Rider's documentation.  Even so, may I suggest you document them in the readme?

May I ask a follow up question?  I can put it in a separate issue if necessary.

In the real application I'm developing, clicking the Edit and Preview or Preview Only buttons still does not show the preview for any of the XAMLs, just a blank grid.  Why might that be?  Might it be significant that all the XAMLs are UserControls, except for MainWindow, which hosts the UserControls by binding to their view models?

**Comment by ForNeVeR** [comment] 2024-04-19 20:37
Let's proceed in this issue. I'd start by looking at the log of the previewer (click a console button in its editor part to see it): does it print any errors or warnings?

**Comment by SimonORorke** [comment] 2024-04-19 21:37
Here's the log, for either `MainWindow` or a `UserControl`:
```
Initializing application in design mode
Obtaining AppBuilder instance from FalconProgrammer.Program
Sending StartDesignerSessionMessage
```

**Comment by SimonORorke** [comment] 2024-04-19 23:01
Here's one more thing, in case it is relevant. The view models, via which the `UserControl`s are bound to the `MainWindow`, are in a separate assembly that is referenced by the GUI assembly.

**Comment by ForNeVeR** [comment] 2024-04-20 09:41
Ok, please take a look at the IDE log. It could contain additional information from the previewer process.

**Comment by SimonORorke** [comment] 2024-04-21 20:12
In Rider, I have done Help -> Collect Logs and Diagnostic Data. There are many files here. See attachment.
[rider-logs-20240422-075101805245337859877175.zip](https://github.com/ForNeVeR/AvaloniaRider/files/15053375/rider-logs-20240422-075101805245337859877175.zip)
Is there a specific file or files we need to look at?

**Comment by SimonORorke** [comment] 2024-04-21 22:33
But I've just spotted this "IDE Internal Error", shown  separately by a red icon bottom right on the Rider window.  I cannot replicate the error message after closing and reopening Rider.  So maybe it is not relevant.

Socket error while session is still alive

java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:328)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readBytes(BsonStreamReader.kt:26)
	at me.fornever.avaloniarider.bson.BsonStreamReader.readMessage(BsonStreamReader.kt:30)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSession.processSocketMessages(AvaloniaPreviewerSession.kt:64)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$executePreviewerAsync$sessionJob$1.invoke(AvaloniaPreviewerSessionController.kt:289)
	at me.fornever.avaloniarider.previewer.AvaloniaPreviewerSessionController$executePreviewerAsync$sessionJob$1.invoke(AvaloniaPreviewerSessionController.kt:286)
	at com.intellij.openapi.rd.util.RdCoroutinesUtilKt$startSyncIOBackgroundAsync$1.invokeSuspend(RdCoroutinesUtil.kt:157)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by ForNeVeR** [comment] 2024-04-22 08:54
The real error is
```
XamlX.XamlLoadException: Unable to find public constructor for type FalconProgrammer.ViewModel:FalconProgrammer.ViewModel.MidiForMacrosViewModel() Line 12, position 10.
   at XamlX.Transform.Transformers.ConstructableObjectTransformer.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlPropertyAssignmentNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.VisitList[T](IList`1 list, IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstConstructableObjectNode.VisitChildren(IXamlAstVisitor visitor)
   at XamlX.Ast.XamlAstNode.Visit(IXamlAstVisitor visitor)
   at XamlX.Transform.AstTransformationContext.Visit(IXamlAstNode root, IXamlAstTransformer transformer)
   at XamlX.Compiler.XamlCompiler`2.Transform(XamlDocument doc, Boolean strict)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadGroupSreCore(IReadOnlyCollection`1 documents, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSreCore(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.LoadSre(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Markup.Xaml.XamlIl.AvaloniaXamlIlRuntimeCompiler.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.Designer.HostApp.DesignXamlLoader.Load(RuntimeXamlLoaderDocument document, RuntimeXamlLoaderConfiguration configuration)
   at Avalonia.DesignerSupport.DesignWindowLoader.LoadDesignerWindow(String xaml, String assemblyPath, String xamlFileProjectPath, Double renderScaling)
   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.<>c__DisplayClass18_0.<OnTransportMessage>b__0()
```

(see `idea.log`)

Why can it not find the constructor in question I don't know, but this is not an issue with this project; perhaps, there's a problem with Avalonia previewer (please report to Avalonia), or with your markup (something's not correctly instantiated for design time).

I am closing this as a duplicate of #316 for now.

**Closed by ForNeVeR** 2024-04-22 08:54 UTC
Labels: kind:bug, status:waiting-for-info
